skip_non_tags: true

environment:
  nodejs_version: "10.9.0"

platform: x64

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - cmd: git submodule -q update --init --recursive
  - ps: Install-Product node $env:nodejs_version x64
  - cd desktop
  - yarn

build_script:
  - yarn build-prod
  - yarn publish-prod

artifacts:
  - path: '*.exe'
  - path: '*.nupkg'
  - path: RELEASES

deploy:
  release: Version $(version)
  tag: v$(version)
  description: 'Description'
  provider: GitHub
  auth_token:
    secure: yYbqUYxHx57pUoxn+9TzVE3UZWZ73w6vBy6zt276Ft3/uGucBvJBzVtVBDPQAsvu
  artifact: /.*\.exe/,/.*\.nupkg/,RELEASES           
  draft: true
  prerelease: false
  on:
    branch: /v\d+\.\d+\.\d+/
    appveyor_repo_tag: true
